# Generated by Django 4.0.3 on 2022-03-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoform', '0002_alter_register_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='image',
            field=models.ImageField(max_length=15000, upload_to=''),
        ),
    ]
