# Generated by Django 4.0.3 on 2022-03-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoform', '0005_alter_register_file_alter_register_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
