# Generated by Django 4.0.3 on 2022-03-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoform', '0006_alter_register_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='image',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
